Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -73,59 +73,37 @@ jobs:
           ls -R dist
 
 
-      #  Select Server Based on ENV
-      - name: Set Server Config
-        run: |
-          ENV="${{ github.event.inputs.env }}"
-          case "$ENV" in
-            dev)
-              {
-                echo "HOST=${{ secrets.DEV_HOST }}" >> $GITHUB_ENV
-                echo "USER=${{ secrets.DEV_USER }}" >> $GITHUB_ENV
-              } >> $GITHUB_ENV
-              ;;
-            india)
-              {
-                echo "HOST=${{ secrets.INDIA_HOST }}" >> $GITHUB_ENV
-                echo "USER=${{ secrets.INDIA_USER }}" >> $GITHUB_ENV
-              } >> $GITHUB_ENV
-              ;;
-            uk)
-              {
-                echo "HOST=${{ secrets.UK_HOST }}" >> $GITHUB_ENV
-                echo "USER=${{ secrets.UK_USER }}" >> $GITHUB_ENV
-              } >> $GITHUB_ENV
-              ;;
-            *)
-              echo " Invalid environment: $ENV"
-              exit 1
-              ;;
-          esac
-          
-          
 
+      # setup ssh
       - name: Setup SSH
         run: |
           mkdir -p ~/.ssh
-          ENV="${{ github.event.inputs.env }}"
 
-          case "$ENV" in
-            dev)
-              printf "%s" "${{ secrets.DEV_KEY }}" > ~/.ssh/id_rsa
-              ;;
-            india)
-              printf "%s" "${{ secrets.INDIA_KEY }}" > ~/.ssh/id_rsa
-              ;;
-            uk)
-              printf "%s" "${{ secrets.UK_KEY }}" > ~/.ssh/id_rsa
-              ;;
-            *)
-              echo "Invalid environment: $ENV"
-              exit 1
-              ;;
-          esac
+          ENV="${{ github.event.inputs.env }}"
+          echo "ENV = $ENV"
+
+          if [ "$ENV" = "dev" ]; then
+            printf "%s" "${{ secrets.DEV_KEY }}" > ~/.ssh/id_rsa
+            HOST="${{ secrets.DEV_HOST }}"
+            USER="${{ secrets.DEV_USER }}"
+          elif [ "$ENV" = "india" ]; then
+            printf "%s" "${{ secrets.INDIA_KEY }}" > ~/.ssh/id_rsa
+            HOST="${{ secrets.INDIA_HOST }}"
+            USER="${{ secrets.INDIA_USER }}"
+          elif [ "$ENV" = "uk" ]; then
+            printf "%s" "${{ secrets.UK_KEY }}" > ~/.ssh/id_rsa
+            HOST="${{ secrets.UK_HOST }}"
+            USER="${{ secrets.UK_USER }}"
+          else
+            echo "Invalid environment: $ENV"
+            exit 1
+          fi
+
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
+
+          echo "HOST=$HOST" >> $GITHUB_ENV
+          echo "USER=$USER" >> $GITHUB_ENV
 
 
           
